SECRET_KEY = "SystemLight"
JSON_AS_ASCII = False

DATABASE_FILE = "foo.db"
SQLALCHEMY_DATABASE_URI = f"sqlite:///{DATABASE_FILE}"
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False

FLASK_ADMIN_SWATCH = "cerulean"
